//based on the example generated by the App...

let serial;
let latestData = "waiting for data";

let xMark;
let prevXMark;
let yMark;
let prevYMark;
let bckgrndColor;
let pMark;
let img1;


let portName = '/dev/tty.usbmodem14101';//update this with the port you are using

function preload() {
  img = loadImage('breathe.jpg');
}

function setup() {
createCanvas(windowWidth, windowHeight);
bckgrndColor = color( random(255), random(255), random(255) )
background(bckgrndColor);

	xMark = width/2;
	yMark = height/2;

 serial = new p5.SerialPort();

 serial.list();
 serial.open(portName);

 serial.on('connected', serverConnected);

 serial.on('list', gotList);

 serial.on('data', gotData);

 serial.on('error', gotError);

 serial.on('open', gotOpen);

 serial.on('close', gotClose);
}

function serverConnected() {
 print("Connected to Server");
}

function gotList(thelist) {
 print("List of Serial Ports:");

 for (let i = 0; i < thelist.length; i++) {
  print(i + " " + thelist[i]);
 }
}

function gotOpen() {
 print("Serial Port is Open");
}

function gotClose(){
 print("Serial Port is Closed");
 latestData = "Serial Port is Closed";
}

function gotError(theerror) {
 print(theerror);
}

function gotData() {
 let currentString = serial.readLine();
  trim(currentString);//trim removes white spaces
 if (!currentString) return;
 //console.log(currentString);
 latestData = currentString.split(',');
 //console.log(latestData);
}

function draw() {
prevXMard = xMark;
xMark = constrain (map (latestData[0], 0,1023, 0,width),0,width);

prevYMark = yMark;
yMark = constrain (map (latestData[1], 0,1023, 0,height),0,height);
// if statement for the xMark


let a = xMark;
if (a > 400) {
  console.log('positive');
  fill(182, 120, 120);
  ellipse(xMark, yMark, 50, 20);
} else {
  console.log('negative');
  square(xMark, yMark, 100, 20);
}

let z = yMark;
if (z > 800) {
  console.log('positive');
  fill(120, 174, 182);
  ellipse(xMark, yMark, 50, 20);
  display(img1);
} else {
  console.log('negative');
  rect(yMark, xMark, 120, 20, 10);
}
}

function mousePressed(){
	bckgrndColor = color(random(255),random(255),random(255) );
}


function keyPressed(){
	if(key == 'l'){
		writeSerial(key);
	}
}

function writeSerial(writeOut){
	serial.write(writeOut);
}
